name: Deploy to Render

on:
  pull_request:
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '1.17'

    - name: Build and package the Spring application
      run: |
        ./mvnw clean package
      working-directory: ApifFirebase

    - name: Render Deploy Action
      # You may pin to the exact commit or the version.
      # uses: johnbeynon/render-deploy-action@a0588f9aca995a15d69a72cb2bfbf37c12e5b540
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
      # ID of the service to deploy
        service-id: ${{secrets.SERVICE_ID_DEV}}
        api-key: ${{secrets.RENDER_APY_KEY}}

    # - name: Deploy to Render
    #   if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'DEV' && github.event.pull_request.merged_by
    #   env:
    #     RENDER_TOKEN: ${{ secrets.RENDER_TOKEN }}
    #   run: |
    #     curl -X POST -H "Authorization: Bearer $RENDER_TOKEN" https://api.render.com/v1/services/SERVICE_ID/deploy
